name: nature-paper-code
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - scikit-learn
  - papermill
  - bioconda::mageck  # MAGeCK (if available via bioconda for your platform)
  - pip
  - pip:
      - polars
      - plotnine